import { Body, Controller, Delete, Get, Param, Post, Req, UseGuards } from '@nestjs/common';
import { AuthGuard } from '../auth/auth.guard';
import { Roles } from '../auth/roles.decorator';
import { RolesGuard } from '../auth/roles.guard';
import { AutoAssignDto } from './dto/auto-assign.dto';
import { AutoGenerateDto } from './dto/auto-generate.dto';
import { CreateTeamDto } from './dto/create-team.dto';
import { TeamsService } from './teams.service';

@Controller('teams')
@UseGuards(AuthGuard)
export class TeamsController {
  constructor(private readonly teamsService: TeamsService) {}

  @Get()
  @Roles('admin')
  @UseGuards(RolesGuard)
  findAll() {
    return this.teamsService.findAll();
  }

  @Post()
  @Roles('admin')
  @UseGuards(RolesGuard)
  create(@Body() dto: CreateTeamDto, @Req() req: any) {
    return this.teamsService.create(dto.name, req.user.id);
  }

  @Delete(':id')
  @Roles('admin')
  @UseGuards(RolesGuard)
  delete(@Param('id') id: string) {
    return this.teamsService.delete(id);
  }

  @Post('auto-generate')
  @Roles('admin')
  @UseGuards(RolesGuard)
  autoGenerate(@Body() dto: AutoGenerateDto) {
    return this.teamsService.autoGenerate(dto.teamSize ?? 4, dto.filterPromo, dto.filterSpecialty);
  }

  @Post('auto-assign')
  @Roles('admin')
  @UseGuards(RolesGuard)
  autoAssign(@Body() dto: AutoAssignDto) {
    return this.teamsService.autoAssign(dto.teams);
  }
}
