import { IsInt, IsOptional, IsPositive, IsString } from 'class-validator';

export class AutoGenerateDto {
  @IsInt()
  @IsPositive()
  @IsOptional()
  teamSize?: number;

  @IsString()
  @IsOptional()
  filterPromo?: string;

  @IsString()
  @IsOptional()
  filterSpecialty?: string;
}
